apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generic-pvc
  namespace: jboss-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard