apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
data:
  # Secrets should be base64 encoded. 
  # Example: echo -n 'my-super-secret-password' | base64
  DB_PASSWORD: "bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk"
