apiVersion: v1
kind: Service
metadata:
  name: my-stateful-app-headless
spec:
  clusterIP: None
  selector:
    app: my-stateful-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: my-stateful-app-service
spec:
  selector:
    app: my-stateful-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
